[profile.default]
solc = '0.8.23'
evm_version = 'paris'
src = "src"
out = "out"
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
