[profile.default]
solc = '0.8.23'
evm_version = 'paris'
src = "src"
out = "out"
libs = ["lib", "node_modules"]
build_info = true
extra_output = ['storageLayout']
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
ethereum ="${RPC_ETHEREUM_MAINNET}"
optimism = "${RPC_OPTIMISM_MAINNET}"
polygon = "${RPC_POLYGON_MUMBAI}"
ethereum_sepolia ="${RPC_ETHEREUM_SEPOLIA}"
optimism_sepolia = "${RPC_OPTIMISM_SEPOLIA}"
polygon_mumbai = "${RPC_POLYGON_MUMBAI}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
